### ISSUE TITLE
broken on modern versions of Node?

### ISSUE THREAD

**Issue by qhenkart** [vishvish/node-watermarker-native#2]
npm install watermarker

> watermarker@1.0.2 install /Users/qhenkart/workspace/allflags/allflags/node_modules/watermarker
> node-gyp rebuild

  CXX(target) Release/obj.target/watermarker/src/watermarker.o
../src/watermarker.cc:22:31: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Watermark(const Arguments& args) {
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/qhenkart/.node-gyp/4.2.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/watermarker.cc:23:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/qhenkart/.node-gyp/4.2.0/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/watermarker.cc:25:48: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  Local<Object> obj = Local<Object>::Cast( args[ 0 ] );
                                           ~~~~^ ~
../src/watermarker.cc:26:72: error: no member named 'NewSymbol' in 'v8::String'
  Local<Object> imageData     = Local<Object>::Cast( obj->Get( String::NewSymbol("imageData") ) );
                                                               ~~~~~~~~^
../src/watermarker.cc:27:72: error: no member named 'NewSymbol' in 'v8::String'
  Local<Object> watermarkData = Local<Object>::Cast( obj->Get( String::NewSymbol("watermarkData") ) );
                                                               ~~~~~~~~^
../src/watermarker.cc:30:12: error: no member named 'New' in 'v8::String'
    return THROW_ERROR_EXCEPTION("composite()'s 1st argument should have \"imageData\" key with a Buffer instance");
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:13:78: note: expanded from macro 'THROW_ERROR_EXCEPTION'
# define THROW_ERROR_EXCEPTION(x) ThrowException(v8::Exception::Error(String::New(x))); \

```
                                                                 ~~~~~~~~^
```

../src/watermarker.cc:30:12: error: no member named 'Close' in 'v8::HandleScope'
    return THROW_ERROR_EXCEPTION("composite()'s 1st argument should have \"imageData\" key with a Buffer instance");
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:14:9: note: expanded from macro 'THROW_ERROR_EXCEPTION'
  scope.Close(Undefined())

``` ^
../src/watermarker.cc:30:12: error: no matching function for call to 'Undefined'
    return THROW_ERROR_EXCEPTION("composite()'s 1st argument should have \"imageData\" key with a Buffer instance");
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:14:15: note: expanded from macro 'THROW_ERROR_EXCEPTION'
  scope.Close(Undefined())
              ^~~~~~~~~
/Users/qhenkart/.node-gyp/4.2.0/include/node/v8.h:315:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Local<Primitive> Undefined(Isolate* isolate);
                          ^
../src/watermarker.cc:33:33: error: no member named 'NewSymbol' in 'v8::String'
  int debug = obj->Get( String::NewSymbol("debug") )->Uint32Value();
                        ~~~~~~~~^
../src/watermarker.cc:46:12: error: no member named 'New' in 'v8::String'
    return THROW_ERROR_EXCEPTION(message.c_str());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:13:78: note: expanded from macro 'THROW_ERROR_EXCEPTION'
#define THROW_ERROR_EXCEPTION(x) ThrowException(v8::Exception::Error(String::New(x))); \
                                                                     ~~~~~~~~^
../src/watermarker.cc:46:12: error: no member named 'Close' in 'v8::HandleScope'
    return THROW_ERROR_EXCEPTION(message.c_str());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:14:9: note: expanded from macro 'THROW_ERROR_EXCEPTION'
  scope.Close(Undefined())
  ~~~~~ ^
../src/watermarker.cc:46:12: error: no matching function for call to 'Undefined'
    return THROW_ERROR_EXCEPTION(message.c_str());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:14:15: note: expanded from macro 'THROW_ERROR_EXCEPTION'
  scope.Close(Undefined())
              ^~~~~~~~~
/Users/qhenkart/.node-gyp/4.2.0/include/node/v8.h:315:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Local<Primitive> Undefined(Isolate* isolate);
                          ^
../src/watermarker.cc:49:12: error: no member named 'New' in 'v8::String'
    return THROW_ERROR_EXCEPTION("unhandled error");
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:13:78: note: expanded from macro 'THROW_ERROR_EXCEPTION'
#define THROW_ERROR_EXCEPTION(x) ThrowException(v8::Exception::Error(String::New(x))); \
                                                                     ~~~~~~~~^
../src/watermarker.cc:49:12: error: no member named 'Close' in 'v8::HandleScope'
    return THROW_ERROR_EXCEPTION("unhandled error");
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:14:9: note: expanded from macro 'THROW_ERROR_EXCEPTION'
  scope.Close(Undefined())
  ~~~~~ ^
../src/watermarker.cc:49:12: error: no matching function for call to 'Undefined'
    return THROW_ERROR_EXCEPTION("unhandled error");
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:14:15: note: expanded from macro 'THROW_ERROR_EXCEPTION'
  scope.Close(Undefined())
              ^~~~~~~~~
/Users/qhenkart/.node-gyp/4.2.0/include/node/v8.h:315:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Local<Primitive> Undefined(Isolate* isolate);
                          ^
../src/watermarker.cc:59:12: error: no member named 'New' in 'v8::String'
    return THROW_ERROR_EXCEPTION(message.c_str());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:13:78: note: expanded from macro 'THROW_ERROR_EXCEPTION'
#define THROW_ERROR_EXCEPTION(x) ThrowException(v8::Exception::Error(String::New(x))); \
                                                                     ~~~~~~~~^
../src/watermarker.cc:59:12: error: no member named 'Close' in 'v8::HandleScope'
    return THROW_ERROR_EXCEPTION(message.c_str());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:14:9: note: expanded from macro 'THROW_ERROR_EXCEPTION'
  scope.Close(Undefined())
  ~~~~~ ^
../src/watermarker.cc:59:12: error: no matching function for call to 'Undefined'
    return THROW_ERROR_EXCEPTION(message.c_str());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:14:15: note: expanded from macro 'THROW_ERROR_EXCEPTION'
  scope.Close(Undefined())
              ^~~~~~~~~
/Users/qhenkart/.node-gyp/4.2.0/include/node/v8.h:315:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Local<Primitive> Undefined(Isolate* isolate);
                          ^
../src/watermarker.cc:62:12: error: no member named 'New' in 'v8::String'
    return THROW_ERROR_EXCEPTION("unhandled error");
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/watermarker.cc:13:78: note: expanded from macro 'THROW_ERROR_EXCEPTION'
#define THROW_ERROR_EXCEPTION(x) ThrowException(v8::Exception::Error(String::New(x))); \
                                                                     ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/watermarker/src/watermarker.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/qhenkart/workspace/allflags/allflags/node_modules/watermarker
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "install" "watermarker"
npm ERR! node v4.2.0
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE

npm ERR! watermarker@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the watermarker@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the watermarker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls watermarker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by vishvish** [comment]
I recall that the extension API changed completely with Node 0.12 - just going to clone this repo and see what's up.

**Comment by vishvish** [comment]
Hmm, just looked at it, and yes indeed, there's some major V8 changes, literally all the calls. I've just bootstrapped a simple C++ addon with Node 5.0.0, however, so I may be able to simply hook into the new API calls very easily. I've just installed GraphicsMagick from source to pick up the includes, and that worked first time, so it bodes well. I'll find some time to take a deeper dive today.

**Comment by vishvish** [comment]
So I refactored the code and got most of the issues out of watermarking... So I thought, but my tests don't work - I'm unable to write out an image from the returned buffer to see the watermarks. Is anyone up for looking at the code if I push the branch?

**Comment by vishvish** [comment]
Just pushed some code WIP to try and make it work - it compiles, but unable to get my tests running - maybe someone can take a look and suggest something?
